# Dockerfile
FROM phusion/passenger-ruby27

MAINTAINER bhagyesh.raut@joshsoftware.com

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# Expose Nginx HTTP service
EXPOSE 80

# Start Nginx / Passenger
RUN rm -f /etc/service/nginx/down

# Remove the default site
RUN rm /etc/nginx/sites-enabled/default

# Add the nginx site and config
ADD nginx.conf /etc/nginx/sites-enabled/webapp.conf

RUN gem install bundler

RUN bash -lc 'rvm install ruby-2.7.1'
RUN bash -lc 'rvm --default use ruby-2.7.1'

RUN apt-get update -y
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash
RUN apt-get install -y tzdata nodejs
RUN npm install --global yarn


# Install bundle of gems
WORKDIR /tmp
ADD railsapp/Gemfile /tmp/
ADD railsapp/Gemfile.lock /tmp/
RUN bundle install

# Add the Rails app
ADD railsapp /home/app/webapp
RUN chown -R app:app /home/app/webapp

WORKDIR /home/app/webapp
# Clean up APT and bundler when done.
RUN yarn install --check-files
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ENV RAILS_ENV=development